### ISSUE TITLE
Ability to have days with no reading

### ISSUE THREAD

**Issue by eatingistheway** [armadellis24/bibleapp#5]
In the plan.json file, the elements in the list refer to chapters in the Bible. Is it possible to add a "skip day"? Screenshots attached
![Screenshot 2021-01-21 232556](https://user-images.githubusercontent.com/21974428/105446456-239baf80-5c40-11eb-8de6-c2285db2f2b2.jpg)
![Screenshot 2021-01-21 232615](https://user-images.githubusercontent.com/21974428/105446461-24ccdc80-5c40-11eb-8abf-fe7ae9874528.jpg)

**Comment by dinushkaherath** [comment]
Yes for sure! I'll add "Catch up day" into an exception area, what should I display? A verse about resting in the Lord? :D

**Comment by eatingistheway** [comment]
Sure! That should be fine

**Comment by dinushkaherath** [comment]
All done

**Comment by dinushkaherath** [comment]
@eatingistheway merge addCatchUpDays branch into your repo
for adding catchup days and makings sure all books have a 1 as the chapter (ie Jude)
